model_name: t5-small
output_dir: runs/exp_rae_t5s

# Usa TODOS los shards que vayas creando:
train_blocks_dir: data/rae_holdout/blocks_data
dedup_train: true

# Tus dev/test fijos (holdout que NO regeneras):
dev_path:  data/rae_holdout/dev.jsonl
test_path: data/rae_holdout/test.jsonl

max_source_length: 96
max_target_length: 64
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
num_train_epochs: 6
learning_rate: 0.0005
warmup_ratio: 0.04
weight_decay: 0.01
seed: 42
gradient_checkpointing: false
strip_accents_targets: true

# ponderación del '#'
upweight_hash_tokens: true
hash_weight: 3.0
