model_name: t5-small
output_dir: runs/exp_cpu_t5s_fixed

max_source_length: 96
max_target_length: 64

per_device_train_batch_size: 8
per_device_eval_batch_size: 8
grad_accum_steps: 1

learning_rate: 5e-4     # baja desde 1e-3
num_train_epochs: 6

logging_steps: 100
evaluation_strategy: epoch   # (lo coge train.py)
warmup_ratio: 0.05
weight_decay: 0.01

fp16: false
gradient_checkpointing: false
report_to: "none"
save_total_limit: 2
