# configs/training_mini.yaml
model_name: t5-small
output_dir: runs/mini_overfit
train_path: data/synthetic/mini.jsonl
dev_path:   data/synthetic/mini.jsonl
test_path:  data/synthetic/mini.jsonl

max_source_length: 96
max_target_length: 64

per_device_train_batch_size: 16
per_device_eval_batch_size: 16

optim: adafactor
learning_rate: 1e-3
num_train_epochs: 30

evaluation_strategy: epoch
save_strategy: no

warmup_ratio: 0.0
weight_decay: 0.0
fp16: false
bf16: false
gradient_checkpointing: false
seed: 42
report_to: "none"
